FPS = 60
UPDATE_RATE = 150  # in milliseconds

# DISPLAY_WIDTH = 250
# DISPLAY_HEIGHT = 500
# DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
# CELL_SIZE = DISPLAY_HEIGHT//20
CELL_SIZE = 30
CELLS_IN_HORIZONTAL = 10
CELLS_IN_VERTICAL = 20
DISPLAY_WIDTH = CELLS_IN_HORIZONTAL * CELL_SIZE
DISPLAY_HEIGHT = CELLS_IN_VERTICAL * CELL_SIZE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)


# COLORS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255,255,0)
TETROMINO_COLORS = (RED, GREEN, BLUE, YELLOW)
